import { CatalogEntryType, FlavorNoteCategory, FlavorNoteType, PrismaClient, ProfileSource, ProfileStatus } from "@prisma/client";
import { validateFlavor } from "../src/lib/flavors/validate-flavor";
import type { FlavorProfile } from "../src/lib/flavors/types";

const prisma = new PrismaClient();
type SeedNote = [name:string, slug:string, category:FlavorNoteCategory, intensity:number, noteType:FlavorNoteType];
type SeedFlavor = { brand:string;brandSlug:string;name:string;slug:string;description:string;profile:FlavorProfile;notes:SeedNote[];catalogEntryType?:CatalogEntryType };
const profile=(values:Partial<FlavorProfile>):FlavorProfile=>({sweetness:5,acidity:2,bitterness:1,creaminess:1,cooling:0,strength:5,intensity:6,heatResistance:7,dryness:2,juiciness:5,freshness:3,dessertLevel:3,spiceLevel:0,floralLevel:0,herbalLevel:0,smokyLevel:0,naturalness:6,persistence:6,...values});
const n=(name:string,category:FlavorNoteCategory,intensity:number,noteType:FlavorNoteType,slug=name.toLowerCase().replace(/\s+/g,"-")):SeedNote=>[name,slug,category,intensity,noteType];

const flavors:SeedFlavor[]=[
 {brand:"Overdose",brandSlug:"overdose",name:"Coffee",slug:"coffee",description:"Насыщенный кофейный вкус с нотами обжарки и лёгкой шоколадной горечью.",profile:profile({strength:8,heatResistance:7,intensity:9,sweetness:3,acidity:2,cooling:0,creaminess:2,bitterness:7,dryness:6,juiciness:2,freshness:1,dessertLevel:5,smokyLevel:7,naturalness:7,persistence:9}),notes:[n("coffee",FlavorNoteCategory.COFFEE,10,FlavorNoteType.DOMINANT),n("roasted",FlavorNoteCategory.SMOKY,8,FlavorNoteType.SECONDARY),n("dark chocolate",FlavorNoteCategory.CHOCOLATE,5,FlavorNoteType.SECONDARY),n("dessert",FlavorNoteCategory.DESSERT,4,FlavorNoteType.ACCENT)]},
 {brand:"HIT",brandSlug:"hit",name:"Banana Shake",slug:"banana-shake",description:"Сладкий банановый вкус со сливочными и ванильными нотами.",profile:profile({strength:5,heatResistance:6,intensity:6,sweetness:8,acidity:1,cooling:0,creaminess:8,bitterness:1,dryness:1,juiciness:7,freshness:2,dessertLevel:9,naturalness:6,persistence:6}),notes:[n("banana",FlavorNoteCategory.FRUIT,10,FlavorNoteType.DOMINANT),n("vanilla",FlavorNoteCategory.DESSERT,7,FlavorNoteType.SECONDARY),n("cream",FlavorNoteCategory.DAIRY,8,FlavorNoteType.SECONDARY),n("dessert",FlavorNoteCategory.DESSERT,7,FlavorNoteType.ACCENT)]},
 {brand:"Element",brandSlug:"element",name:"Мята",slug:"mint",description:"Чистая прохладная мята с травяным оттенком.",profile:profile({strength:4,heatResistance:8,intensity:8,sweetness:2,acidity:1,cooling:9,creaminess:0,bitterness:2,dryness:4,juiciness:3,freshness:10,herbalLevel:7,naturalness:7,persistence:8}),notes:[n("mint",FlavorNoteCategory.COOLING,10,FlavorNoteType.DOMINANT),n("herbal",FlavorNoteCategory.HERBAL,5,FlavorNoteType.SECONDARY)]},
 {brand:"Musthave",brandSlug:"musthave",name:"Манго",slug:"mango",description:"Спелое сочное манго с тропической сладостью.",profile:profile({strength:6,heatResistance:8,intensity:8,sweetness:8,acidity:4,cooling:0,creaminess:2,bitterness:1,dryness:1,juiciness:10,freshness:6,dessertLevel:4,naturalness:7,persistence:8}),notes:[n("mango",FlavorNoteCategory.FRUIT,10,FlavorNoteType.DOMINANT),n("tropical",FlavorNoteCategory.TROPICAL,7,FlavorNoteType.SECONDARY)]},
 {brand:"Darkside",brandSlug:"darkside",name:"Кокос",slug:"coconut",description:"Мягкий кокос с умеренной десертной сладостью.",profile:profile({strength:7,heatResistance:8,intensity:6,sweetness:7,acidity:1,cooling:0,creaminess:7,bitterness:2,dryness:3,juiciness:4,freshness:2,dessertLevel:8,naturalness:6,persistence:7}),notes:[n("coconut",FlavorNoteCategory.TROPICAL,10,FlavorNoteType.DOMINANT),n("cream",FlavorNoteCategory.DAIRY,5,FlavorNoteType.SECONDARY)]},
 {brand:"Sebero",brandSlug:"sebero",name:"Лимон",slug:"lemon",description:"Яркий лимон с натуральной цитрусовой кислинкой.",profile:profile({strength:5,heatResistance:7,intensity:8,sweetness:3,acidity:9,cooling:2,creaminess:0,bitterness:2,dryness:3,juiciness:8,freshness:9,naturalness:8,persistence:6}),notes:[n("lemon",FlavorNoteCategory.CITRUS,10,FlavorNoteType.DOMINANT),n("citrus",FlavorNoteCategory.CITRUS,9,FlavorNoteType.SECONDARY)]},
 {brand:"BlackBurn",brandSlug:"blackburn",name:"Ваниль",slug:"vanilla",description:"Тёплая сладкая ваниль для смягчения насыщенных миксов.",profile:profile({strength:6,heatResistance:7,intensity:5,sweetness:8,acidity:0,cooling:0,creaminess:6,bitterness:1,dryness:2,juiciness:3,freshness:1,dessertLevel:10,naturalness:6,persistence:7}),notes:[n("vanilla",FlavorNoteCategory.DESSERT,10,FlavorNoteType.DOMINANT),n("dessert",FlavorNoteCategory.DESSERT,6,FlavorNoteType.SECONDARY)]},
 {brand:"Daily Hookah",brandSlug:"daily-hookah",name:"Сливки",slug:"cream",description:"Нежный сливочный вкус с мягким послевкусием.",profile:profile({strength:4,heatResistance:6,intensity:5,sweetness:6,acidity:0,cooling:0,creaminess:10,bitterness:0,dryness:1,juiciness:4,freshness:1,dessertLevel:9,naturalness:6,persistence:6}),notes:[n("cream",FlavorNoteCategory.DAIRY,10,FlavorNoteType.DOMINANT),n("milk",FlavorNoteCategory.DAIRY,7,FlavorNoteType.SECONDARY)]},
 {brand:"Test Kitchen",brandSlug:"test-kitchen",name:"Dark Chocolate",slug:"dark-chocolate",description:"Тестовый профиль тёмного шоколада с какао и сухой горечью.",profile:profile({sweetness:4,bitterness:8,creaminess:3,intensity:8,heatResistance:8,dryness:7,dessertLevel:8,smokyLevel:3,persistence:9}),notes:[n("dark chocolate",FlavorNoteCategory.CHOCOLATE,10,FlavorNoteType.DOMINANT),n("cocoa",FlavorNoteCategory.CHOCOLATE,8,FlavorNoteType.SECONDARY)],catalogEntryType:CatalogEntryType.TEST},
 {brand:"Test Kitchen",brandSlug:"test-kitchen",name:"Hazelnut",slug:"hazelnut",description:"Тестовый профиль фундука с мягким жареным оттенком.",profile:profile({sweetness:5,bitterness:3,creaminess:5,intensity:7,dryness:5,dessertLevel:7,smokyLevel:3,persistence:7}),notes:[n("hazelnut",FlavorNoteCategory.NUT,10,FlavorNoteType.DOMINANT),n("roasted",FlavorNoteCategory.SMOKY,5,FlavorNoteType.SECONDARY)],catalogEntryType:CatalogEntryType.TEST},
 {brand:"Test Kitchen",brandSlug:"test-kitchen",name:"Strawberry",slug:"strawberry",description:"Тестовый профиль сладкой сочной клубники.",profile:profile({sweetness:8,acidity:4,juiciness:9,freshness:6,intensity:7,naturalness:7}),notes:[n("strawberry",FlavorNoteCategory.BERRY,10,FlavorNoteType.DOMINANT),n("berry",FlavorNoteCategory.BERRY,6,FlavorNoteType.SECONDARY)],catalogEntryType:CatalogEntryType.TEST},
 {brand:"Test Kitchen",brandSlug:"test-kitchen",name:"Raspberry",slug:"raspberry",description:"Тестовый профиль малины с заметной ягодной кислинкой.",profile:profile({sweetness:7,acidity:6,juiciness:8,freshness:7,intensity:8,naturalness:7}),notes:[n("raspberry",FlavorNoteCategory.BERRY,10,FlavorNoteType.DOMINANT),n("berry",FlavorNoteCategory.BERRY,6,FlavorNoteType.SECONDARY)],catalogEntryType:CatalogEntryType.TEST},
 {brand:"Test Kitchen",brandSlug:"test-kitchen",name:"Blueberry",slug:"blueberry",description:"Тестовый профиль черники с мягкой сладостью.",profile:profile({sweetness:7,acidity:3,juiciness:7,freshness:5,intensity:6,naturalness:6}),notes:[n("blueberry",FlavorNoteCategory.BERRY,10,FlavorNoteType.DOMINANT),n("berry",FlavorNoteCategory.BERRY,6,FlavorNoteType.SECONDARY)],catalogEntryType:CatalogEntryType.TEST},
 {brand:"Test Kitchen",brandSlug:"test-kitchen",name:"Lime",slug:"lime",description:"Тестовый профиль лайма с яркой свежей кислотностью.",profile:profile({sweetness:2,acidity:10,bitterness:3,juiciness:8,freshness:10,intensity:9,naturalness:8}),notes:[n("lime",FlavorNoteCategory.CITRUS,10,FlavorNoteType.DOMINANT),n("citrus",FlavorNoteCategory.CITRUS,8,FlavorNoteType.SECONDARY)],catalogEntryType:CatalogEntryType.TEST},
 {brand:"Test Kitchen",brandSlug:"test-kitchen",name:"Cola",slug:"cola",description:"Тестовый профиль колы со сладкими пряными оттенками.",profile:profile({sweetness:8,acidity:3,bitterness:2,intensity:8,dessertLevel:6,spiceLevel:5,freshness:4,persistence:8}),notes:[n("cola",FlavorNoteCategory.DRINK,10,FlavorNoteType.DOMINANT),n("spice",FlavorNoteCategory.SPICE,6,FlavorNoteType.SECONDARY)],catalogEntryType:CatalogEntryType.TEST},
 {brand:"Test Kitchen",brandSlug:"test-kitchen",name:"Cinnamon",slug:"cinnamon",description:"Тестовый профиль тёплой десертной корицы.",profile:profile({sweetness:4,bitterness:3,intensity:8,dryness:6,dessertLevel:6,spiceLevel:10,persistence:9}),notes:[n("cinnamon",FlavorNoteCategory.SPICE,10,FlavorNoteType.DOMINANT),n("spice",FlavorNoteCategory.SPICE,7,FlavorNoteType.SECONDARY)],catalogEntryType:CatalogEntryType.TEST},
 {brand:"Test Kitchen",brandSlug:"test-kitchen",name:"Peach",slug:"peach",description:"Тестовый профиль сочного сладкого персика.",profile:profile({sweetness:8,acidity:3,juiciness:9,freshness:6,intensity:7,naturalness:7}),notes:[n("peach",FlavorNoteCategory.FRUIT,10,FlavorNoteType.DOMINANT),n("fruit",FlavorNoteCategory.FRUIT,6,FlavorNoteType.SECONDARY)],catalogEntryType:CatalogEntryType.TEST},
];

async function main(){
 for(const item of flavors){
  const candidate={...item.profile,name:item.name,slug:item.slug,profileStatus:ProfileStatus.DRAFT,profileSource:ProfileSource.MANUAL,notes:item.notes.map(([name,slug,category,intensity,noteType])=>({note:{name,slug,category},intensity,noteType}))};
  const validation=validateFlavor(candidate); if(!validation.success) throw new Error(`${item.brand} ${item.name}: ${validation.errors.join("; ")}`);
  const brand=await prisma.brand.upsert({where:{slug:item.brandSlug},update:{name:item.brand},create:{name:item.brand,slug:item.brandSlug}});
  const catalogEntryType=item.catalogEntryType??CatalogEntryType.REAL;
  const entryTypeUpdate=item.catalogEntryType?{catalogEntryType:item.catalogEntryType}:{};
  const flavor=await prisma.flavor.upsert({where:{brandId_slug:{brandId:brand.id,slug:item.slug}},update:{name:item.name,description:item.description,...item.profile,profileStatus:ProfileStatus.DRAFT,profileSource:ProfileSource.MANUAL,...entryTypeUpdate},create:{brandId:brand.id,name:item.name,slug:item.slug,description:item.description,...item.profile,profileStatus:ProfileStatus.DRAFT,profileSource:ProfileSource.MANUAL,catalogEntryType}});
  for(const [name,slug,category,intensity,noteType] of item.notes){const note=await prisma.flavorNote.upsert({where:{slug},update:{name,category},create:{name,slug,category}});await prisma.flavorNoteAssignment.upsert({where:{flavorId_flavorNoteId:{flavorId:flavor.id,flavorNoteId:note.id}},update:{intensity,noteType},create:{flavorId:flavor.id,flavorNoteId:note.id,intensity,noteType}})}
 }
}
main().finally(()=>prisma.$disconnect());
