import type { ExpertMixKnowledgeRecord } from "../expert-mix-knowledge";
import type { ExpertMixImportIssue, ExpertMixImportPlan, ExpertMixImportReport, ExpertMixImportOptions, ExpertMixWorkbookInspection, NormalizedMixComponentStagingRecord, NormalizedMixStagingRecord, NormalizedTobaccoStagingRecord } from "./types";

const count = <T>(items: readonly T[], predicate: (item: T) => boolean) => items.filter(predicate).length;
export const createExpertMixImportReport = (inspection: ExpertMixWorkbookInspection, plan: ExpertMixImportPlan, tobacco: readonly NormalizedTobaccoStagingRecord[], mixes: readonly NormalizedMixStagingRecord[], components: readonly NormalizedMixComponentStagingRecord[], records: readonly ExpertMixKnowledgeRecord[], issues: readonly ExpertMixImportIssue[], options: ExpertMixImportOptions): ExpertMixImportReport => ({
  summary: { workbookPath: inspection.workbookPath, workbookName: inspection.workbookName, importedAt: options.importedAt ?? null, sheetsFound: inspection.sheetsFound, sheetsMissing: inspection.sheetsMissing, totalRowsRead: plan.tobaccoRows.length + plan.mixRows.length + plan.componentRows.length, totalRowsIgnored: plan.ignoredRows, totalWarnings: count(issues, item => item.severity === "WARNING"), totalErrors: count(issues, item => item.severity === "ERROR") },
  tobacco: { rowsRead: plan.tobaccoRows.length, imported: tobacco.length, resolved: count(tobacco, item => item.identityStatus === "RESOLVED"), manufacturerOnly: count(tobacco, item => item.identityStatus === "MANUFACTURER_ONLY"), unresolved: count(tobacco, item => item.identityStatus === "UNRESOLVED"), ambiguous: count(tobacco, item => item.identityStatus === "AMBIGUOUS"), invalid: count(issues, item => item.severity === "ERROR" && item.sheet === "ОСНОВНАЯ_БАЗА"), duplicates: count(issues, item => item.code === "DUPLICATE_PRODUCT_CANDIDATE"), catalogFacts: tobacco.reduce((sum, item) => sum + item.catalogFacts.length, 0), realObservations: tobacco.reduce((sum, item) => sum + item.observations.length, 0), externalRatings: tobacco.reduce((sum, item) => sum + item.externalRatings.length, 0), derivedFromTags: tobacco.reduce((sum, item) => sum + item.derivedCharacteristics.filter(value => value.kind === "TAG_CATEGORY").length, 0), preliminaryInferences: tobacco.reduce((sum, item) => sum + item.derivedCharacteristics.filter(value => value.kind === "PRELIMINARY_INFERENCE").length, 0) },
  mixes: { rowsRead: plan.mixRows.length, imported: records.length, verified: count(records, item => item.status === "VERIFIED"), partiallyVerified: count(records, item => item.status === "PARTIALLY_VERIFIED"), draft: count(records, item => item.status === "DRAFT"), disputed: count(records, item => item.status === "DISPUTED"), rejected: count(records, item => item.status === "REJECTED"), archived: count(records, item => item.status === "ARCHIVED"), invalid: count(issues, item => item.code === "DOMAIN_VALIDATION_FAILED" || item.code === "MIX_ID_MISSING" || item.code === "MIX_COMPONENTS_MISSING"), duplicateCandidates: count(issues, item => item.code === "MIX_DUPLICATE_CANDIDATE") },
  components: { rowsRead: plan.componentRows.length, imported: components.length - count(issues, item => item.code === "MIX_COMPONENT_ORPHANED"), resolved: count(components, item => item.identityStatus === "RESOLVED"), manufacturerOnly: count(components, item => item.identityStatus === "MANUFACTURER_ONLY"), unresolved: count(components, item => item.identityStatus === "UNRESOLVED"), ambiguous: count(components, item => item.identityStatus === "AMBIGUOUS"), unchecked: count(components, item => item.identityStatus === "NOT_CHECKED"), invalid: count(issues, item => item.severity === "ERROR" && item.sheet === "Mix_Components"), orphaned: count(issues, item => item.code === "MIX_COMPONENT_ORPHANED") },
  validation: { percentageSumWarnings: count(issues, item => item.code === "PERCENT_SUM_ROUNDING" || item.code === "PERCENT_SUM_MISMATCH"), weightSumWarnings: count(issues, item => item.code === "WEIGHT_SUM_MISMATCH" || item.code === "TOTAL_WEIGHT_MISMATCH"), duplicateWarnings: count(issues, item => item.code.includes("DUPLICATE")), identityWarnings: count(issues, item => item.code.startsWith("IDENTITY_")), missingSourceWarnings: count(issues, item => item.code === "SOURCE_MISSING"), privacyWarnings: count(issues, item => item.code === "PUBLIC_PRIVACY_LEAK" || item.code === "INTERNAL_NOTE_EXPOSED" || item.code === "PRIVATE_URL_EXPOSED") },
  issues,
});
export const serializeExpertMixImportReport = (report: ExpertMixImportReport): string => JSON.stringify(report, null, 2);
